### ISSUE TITLE
Convert wp_die() to an admin notice

### ISSUE THREAD

**Issue by JiveDig** [copyblogger/genesis-connect-woocommerce#30]
Right now if you activate the plugin without Genesis running it calls `wp_die()`. This causes other plugins being activated/updated to stop and also stops any running WP CLI commans, as well as a ton of other things.

I think it's safer/better to just self-deactivate if you try to activate without Genesis, then show an admin notice like, "Genesis Connect for WooCommerce requires the Genesis Framework so it has been deactivated".

**Comment by nickcernis** [comment]
Thanks for the suggestion, @JiveDig — I agree.

As of 4efd3a0 Genesis Connect will show a notice (and remain active, but load nothing more) if Woo is not available, instead of dying and deactivating.

Still needs to be adapted to work for multisite, but will address that in https://github.com/copyblogger/genesis-connect-woocommerce/issues/27.

---

For QA (develop branch):

## Test 1
- Deactivate WooCommerce, leave Genesis Connect active.

## Confirm
- [ ] A notice appears in the admin area prompting you to activate WooCommerce.

## Test 2
Activate WooCommerce and Genesis Connect, switch to Twenty Seventeen.

## Confirm
- [ ] A notice appears in the admin area prompting you to activate a Genesis child theme.

**Comment by swa433** [comment]
@nickcernis Confirmed +1
(for both tests)

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!


Admin notice in result of Test 1:
"Genesis Connect for WooCommerce requires WooCommerce. Please activate WooCommerce or disable Genesis Connect."


Admin notice in result of Test 2:
"Genesis Connect for WooCommerce requires a Genesis child theme. Please activate a Genesis theme or disable Genesis Connect."
