### ISSUE TITLE
Woo product categories have 2 H1 tags

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-connect-woocommerce#4]
@nathanrice Product category pages currently have 2 H1 tags.

![wellness-double-header](https://cloud.githubusercontent.com/assets/1271053/25018813/646242a6-2056-11e7-91c0-f7f6a2f1ba10.png)

```html
<div class="archive-description taxonomy-archive-description taxonomy-description">
<h1 class="archive-title">Sample Products</h1>
</div>
<h1 class="page-title">sample</h1>
```

We need to remove the second H1 in templates.

**Comment by philipboomy** [comment]
Think it is the "genesis-accessibility" that adds the second h1. Any update on this?

**Comment by dreamwhisper** [comment]
@nathanrice I'm still getting a double title on the product categories.

Adding this to the `taxonomy.php` template appears to work:
`remove_action( 'genesis_before_loop', 'genesis_do_taxonomy_title_description', 15 );`

**Comment by nickcernis** [comment]
Confirmed:

<img width="983" alt="product_categories_socks_and_product_categories_socks" src="https://user-images.githubusercontent.com/647669/30715736-4b691bca-9f0f-11e7-85f7-4942f40b6c4e.png">

**Comment by gwashbrook** [comment]
Wouldn't it be more preferable to keep the Genesis Archive Title and Description , and remove the Product Category Title  and Description?

The Genesis / WP archive description editor allows for rich content. Opening the doors for formatting, media library images, video , ( and once filters applied ) shortcodes, autoembeds etc.

**Comment by madriverweb** [comment]
Agree with gwashbrook: Please reinstate the Archive Intro Text regardless of what you do with title, for those of us that lost it in our sites, and because it IS better with formatting, etc., an argument someone else made. Regarding "Name", Archive Heading is better, too, because it can be longer and more descriptive without affecting the navigation (requiring additional clean-up) or the Product Category display that is better with the short "name." If someone fills in the lower fields, they should override the Name and Description. It was simple to hide the duplicate heading "Name" in CSS, but it's time consuming to copy all of our Intro Text into Description, and it doesn't look as good. It doesn't even take manually inserted tags.
